# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: swapi-ws-indra
useDotenv: true
frameworkVersion: '3'
plugins:
  - serverless-auto-swagger
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:sa-east-1:094275984805:table/charactersTable

functions:
  addCharacters:
    handler: src/functions/character.addCharacter
    events:
      - httpApi:
          path: /add/character
          method: post
  listCharacters:
    handler: src/functions/character.allCharacters
    events:
      - httpApi:
          path: /list/characters
          method: get
  getAllPeople:
    handler: src/functions/people.getAllPeople
    events:
      - httpApi:
          path: /swapi/people
          method: get
  getPeople:
    handler: src/functions/people.getPeople
    events:
      - httpApi:
          path: /swapi/people/{id}
          method: get
  getAllPlanets:
    handler: src/functions/planet.getAllPlanets
    events:
      - httpApi:
          path: /swapi/planet
          method: get
  getPlanet:
    handler: src/functions/planet.getPlanet
    events:
      - httpApi:
          path: /swapi/planet/{id}
          method: get
  getAllVehicles:
    handler: src/functions/vehicle.getAllVehicles
    events:
      - httpApi:
          path: /swapi/vehicle
          method: get
  getVehicle:
    handler: src/functions/vehicle.getVehicle
    events:
      - httpApi:
          path: /swapi/vehicle/{id}
          method: get
resources:
  Resources:
    charactersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: charactersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


