// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "swapi-ws-indra",
    "version": "1"
  },
  "paths": {
    "/add/character": {
      "post": {
        "summary": "addCharacters",
        "description": "",
        "operationId": "addCharacters.post./add/character",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/list/characters": {
      "get": {
        "summary": "listCharacters",
        "description": "",
        "operationId": "listCharacters.get./list/characters",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swapi/people": {
      "get": {
        "summary": "getAllPeople",
        "description": "",
        "operationId": "getAllPeople.get./swapi/people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};